services:
  app:
    build:
      context: .
      dockerfile: .docker/app.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - '8000:80'

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '33065:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

